# Generated by Django 5.0.14 on 2026-09-21 07:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('appointments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIQueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(choices=[('chat', 'Dental assistant chat'), ('symptom', 'Symptom analysis'), ('care_plan', 'Care plan'), ('appointment_help', 'Appointment assistance'), ('clinical_summary', 'Clinical summary for dentist')], max_length=20)),
                ('provider', models.CharField(max_length=30)),
                ('model', models.CharField(blank=True, max_length=60)),
                ('prompt_excerpt', models.TextField(blank=True)),
                ('response_excerpt', models.TextField(blank=True)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('succeeded', models.BooleanField(default=True)),
                ('error_message', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI query log',
                'verbose_name_plural': 'AI query logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CarePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_for', models.DateField(default=django.utils.timezone.localdate)),
                ('headline', models.CharField(blank=True, max_length=200)),
                ('daily_routine', models.JSONField(default=list)),
                ('diet_tips', models.JSONField(default=list)),
                ('warning_signs', models.JSONField(default=list)),
                ('next_checkup_advice', models.CharField(blank=True, max_length=200)),
                ('provider', models.CharField(blank=True, max_length=30)),
                ('is_fallback', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_plans', to='accounts.patientprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='New conversation', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SymptomAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.JSONField(default=list)),
                ('description', models.TextField(blank=True)),
                ('pain_level', models.PositiveSmallIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=0)),
                ('duration', models.CharField(choices=[('today', 'Started today'), ('days', 'A few days'), ('weeks', 'A few weeks'), ('months', 'Several months or longer')], default='days', max_length=10)),
                ('has_swelling', models.BooleanField(default=False)),
                ('has_fever', models.BooleanField(default=False)),
                ('difficulty_swallowing', models.BooleanField(default=False)),
                ('urgency', models.CharField(choices=[('ROUTINE', 'Routine - book at your convenience'), ('SOON', 'See a dentist within a few days'), ('URGENT', 'Urgent - see a dentist within 24 hours'), ('EMERGENCY', 'Emergency - seek care immediately')], default='ROUTINE', max_length=10)),
                ('summary', models.TextField(blank=True)),
                ('possible_areas', models.JSONField(default=list)),
                ('self_care_advice', models.JSONField(default=list)),
                ('red_flags', models.JSONField(default=list)),
                ('recommended_within', models.CharField(blank=True, max_length=60)),
                ('suggested_reason', models.CharField(blank=True, max_length=20)),
                ('provider', models.CharField(blank=True, max_length=30)),
                ('is_fallback', models.BooleanField(default=False)),
                ('reviewed_by_dentist', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='symptom_analyses', to='appointments.appointment')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='symptom_analyses', to='accounts.patientprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptom_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Symptom analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Patient / staff'), ('assistant', 'AI assistant')], max_length=10)),
                ('content', models.TextField()),
                ('provider', models.CharField(blank=True, help_text='Which engine produced this answer.', max_length=30)),
                ('model', models.CharField(blank=True, max_length=60)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('is_fallback', models.BooleanField(default=False, help_text='True when the offline rule engine answered.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='aiassistant.conversation')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['conversation', 'created_at'], name='aiassistant_convers_bd7456_idx')],
            },
        ),
    ]
