# Generated by Django 5.0.14 on 2026-09-21 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DentistAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('dentist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='accounts.dentistprofile')),
            ],
            options={
                'verbose_name_plural': 'Dentist availabilities',
                'ordering': ['weekday', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='TimeOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('dentist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_off', to='accounts.dentistprofile')),
            ],
            options={
                'verbose_name_plural': 'Time off',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=20, unique=True)),
                ('scheduled_for', models.DateTimeField()),
                ('duration_minutes', models.PositiveSmallIntegerField(default=30)),
                ('reason', models.CharField(choices=[('CHECKUP', 'Routine check-up'), ('PAIN', 'Tooth pain'), ('CLEANING', 'Scaling / cleaning'), ('FILLING', 'Filling / cavity'), ('ROOT_CANAL', 'Root canal'), ('EXTRACTION', 'Extraction'), ('ORTHODONTIC', 'Braces / aligners'), ('COSMETIC', 'Cosmetic / whitening'), ('FOLLOW_UP', 'Follow-up visit'), ('EMERGENCY', 'Emergency'), ('OTHER', 'Other')], default='CHECKUP', max_length=20)),
                ('symptoms', models.TextField(blank=True, help_text='What the patient described when booking.')),
                ('status', models.CharField(choices=[('PENDING', 'Pending confirmation'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No show')], default='PENDING', max_length=12)),
                ('notes', models.TextField(blank=True, help_text='Internal clinic notes.')),
                ('cancellation_reason', models.CharField(blank=True, max_length=255)),
                ('ai_triage_summary', models.TextField(blank=True, help_text='Preliminary AI guidance captured at booking time.')),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments_booked', to=settings.AUTH_USER_MODEL)),
                ('dentist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='accounts.dentistprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='accounts.patientprofile')),
            ],
            options={
                'ordering': ['-scheduled_for'],
                'indexes': [models.Index(fields=['scheduled_for'], name='appointment_schedul_fa8dbb_idx'), models.Index(fields=['status'], name='appointment_status_8fe9d7_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['PENDING', 'CONFIRMED'])), fields=('dentist', 'scheduled_for'), name='unique_active_slot_per_dentist'),
        ),
        migrations.AddConstraint(
            model_name='dentistavailability',
            constraint=models.UniqueConstraint(fields=('dentist', 'weekday', 'start_time'), name='unique_dentist_weekday_start'),
        ),
    ]
