# Generated by Django 5.0.14 on 2026-09-21 07:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('appointments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DentalHistoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('MEDICAL', 'Medical condition'), ('DENTAL', 'Past dental treatment'), ('ALLERGY', 'Allergy'), ('SURGERY', 'Surgery'), ('HABIT', 'Habit'), ('OTHER', 'Other')], default='DENTAL', max_length=10)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('recorded_on', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='accounts.patientprofile')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_entries_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Dental history entries',
                'ordering': ['-recorded_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_on', models.DateField(default=django.utils.timezone.localdate)),
                ('advice', models.TextField(blank=True, help_text='Diet, rinsing and aftercare advice.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dentist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='accounts.dentistprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='accounts.patientprofile')),
            ],
            options={
                'ordering': ['-issued_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=120)),
                ('dosage', models.CharField(help_text='e.g. 500 mg', max_length=80)),
                ('frequency', models.CharField(help_text='e.g. Twice daily after meals', max_length=80)),
                ('duration', models.CharField(help_text='e.g. 5 days', max_length=60)),
                ('instructions', models.CharField(blank=True, max_length=200)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='records.prescription')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_date', models.DateField(default=django.utils.timezone.localdate)),
                ('chief_complaint', models.CharField(blank=True, help_text="In the patient's own words.", max_length=255)),
                ('diagnosis', models.TextField()),
                ('procedure', models.CharField(choices=[('CONSULT', 'Consultation'), ('SCALING', 'Scaling and polishing'), ('FILLING', 'Composite filling'), ('RCT', 'Root canal treatment'), ('CROWN', 'Crown / cap'), ('EXTRACTION', 'Extraction'), ('IMPLANT', 'Implant'), ('BRACES', 'Orthodontic treatment'), ('WHITENING', 'Teeth whitening'), ('GUM_TREATMENT', 'Gum treatment'), ('DENTURE', 'Denture'), ('XRAY', 'X-ray / imaging'), ('OTHER', 'Other')], default='CONSULT', max_length=20)),
                ('tooth_region', models.CharField(choices=[('UR', 'Upper right'), ('UL', 'Upper left'), ('LL', 'Lower left'), ('LR', 'Lower right'), ('FM', 'Full mouth'), ('NA', 'Not applicable')], default='NA', max_length=2)),
                ('tooth_numbers', models.CharField(blank=True, help_text='FDI notation, comma separated (e.g. 16, 17).', max_length=60)),
                ('treatment_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='COMPLETED', max_length=12)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('follow_up_instructions', models.TextField(blank=True)),
                ('follow_up_reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatments', to='appointments.appointment')),
                ('dentist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treatments', to='accounts.dentistprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='accounts.patientprofile')),
            ],
            options={
                'ordering': ['-treatment_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='prescription',
            name='treatment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='records.treatment'),
        ),
        migrations.AddIndex(
            model_name='treatment',
            index=models.Index(fields=['treatment_date'], name='records_tre_treatme_9899ef_idx'),
        ),
    ]
